configs : remove scheduler cause error on compiler
error: use of undeclared identifier 'SCHED_CPUFREQ_INTERCLUSTER_MIG'
 2325 |         unsigned int exception_flags = SCHED_CPUFREQ_INTERCLUSTER_MIG |
      |                                        ^
../drivers/misc/mediatek/include/../../../../kernel/sched/sched.h:2326:5: error: use of undeclared identifier 'SCHED_CPUFREQ_PL'
 2326 |                                 SCHED_CPUFREQ_PL | SCHED_CPUFREQ_EARLY_DET;
      |                                 ^
../drivers/misc/mediatek/include/../../../../kernel/sched/sched.h:2326:24: error: use of undeclared identifier 'SCHED_CPUFREQ_EARLY_DET'
 2326 |                                 SCHED_CPUFREQ_PL | SCHED_CPUFREQ_EARLY_DET;
      |                                                    ^
../drivers/misc/mediatek/include/../../../../kernel/sched/sched.h:2332:16: error: use of undeclared identifier 'SCHED_CPUFREQ_WALT'
 2332 |         if (!(flags & SCHED_CPUFREQ_WALT))
      |                       ^
../drivers/misc/mediatek/include/../../../../kernel/sched/sched.h:2335:8: error: no member named 'load_reported_window' in 'struct rq'
 2335 |                 (rq->load_reported_window == rq->window_start) &&
      |                  ~~  ^
../drivers/misc/mediatek/include/../../../../kernel/sched/sched.h:2334:7: error: use of undeclared identifier 'sched_disable_window_stats'
 2334 |         if (!sched_disable_window_stats &&
      |              ^
../drivers/misc/mediatek/include/../../../../kernel/sched/sched.h:2338:6: error: no member named 'load_reported_window' in 'struct rq'
 2338 |         rq->load_reported_window = rq->window_start;
      |         ~~  ^
7 errors generated.

Signed-off-by: Stey Histeria <153775773+Steyhist@users.noreply.github.com>